spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1/security?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML5
server:
  port: 9000


